name:                blog-server
version:             0.1.0.0
github:              "davidwangd/blog-server"
license:             BSD-3-Clause
author:              "Yuanwei Wang"
maintainer:          "davidwangnoi@163.com"
copyright:           "2025 Yuanwei Wang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidwangd/blog-server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.0
- sqlite-simple >= 0.4
- pandoc >= 2.0
- blaze-html >= 0.9 && < 1
- string-convert == 4.0.0.1
- hspec >= 2.11
- happstack-server >= 7.8
- text == 2.1.1
- QuickCheck == 2.14.3
- template-haskell >= 2.0 && < 3
- data-default >= 0.7.1.3
- split == 0.2.5
- process >= 1.6 && <= 2
- safe >= 0.3 && < 0.4
- jwt >= 0.10 && < 1
- mtl == 2.3.1
- time == 1.12.2
- filepath >= 1.4 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  package: blog-server
  source-dirs: src

executables:
  blog-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-server

tests:
  blog-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-server
